#!/usr/bin/env bash
# Download Pretendard, Noto Serif KR, JetBrains Mono for offline use.
# Generates assets/fonts/offline.css with @font-face declarations.
#
# Idempotent: skips files that already exist.

set -euo pipefail

HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(dirname "$HERE")"
FONTS="$ROOT/assets/fonts"

mkdir -p "$FONTS/pretendard" "$FONTS/noto-serif-kr" "$FONTS/jetbrains-mono"

fetch() {
  local url="$1"
  local dest="$2"
  if [[ -f "$dest" ]]; then
    echo "  (exists) $dest"
    return
  fi
  if command -v curl >/dev/null 2>&1; then
    curl -sSL -o "$dest" "$url"
  else
    wget -q -O "$dest" "$url"
  fi
  echo "  fetched  $dest"
}

echo "▸ Pretendard Variable"
PRETENDARD_BASE="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/packages/pretendard/dist/public/variable"
fetch "$PRETENDARD_BASE/PretendardVariable.woff2" "$FONTS/pretendard/PretendardVariable.woff2"
fetch "https://raw.githubusercontent.com/orioncactus/pretendard/v1.3.9/LICENSE" "$FONTS/pretendard/LICENSE"

echo "▸ Noto Serif KR"
# Google Fonts doesn't serve direct woff2 URLs stably; use the raw github repo.
NOTO_BASE="https://raw.githubusercontent.com/notofonts/noto-cjk/main/Serif/Variable/TTF/Subset"
# Static weights (simpler for @font-face than variable TTFs in CSS)
NOTO_GOOGLE="https://fonts.gstatic.com/s/notoserifkr"
# We use the Google-hosted static woff2 because it's reliable.
fetch "$NOTO_GOOGLE/v34/3Jn7SDn90Gmq2mr3blnHaTZXduZp1ODBPnnDGxuhhYaOKwqBf9Z9.woff2" "$FONTS/noto-serif-kr/NotoSerifKR-Light.woff2"
fetch "$NOTO_GOOGLE/v34/3Jn7SDn90Gmq2mr3blnHaTZXduZp1ODBPnnDGxuhhYaO6QuBf9Z9.woff2" "$FONTS/noto-serif-kr/NotoSerifKR-Medium.woff2"
fetch "$NOTO_GOOGLE/v34/3Jn7SDn90Gmq2mr3blnHaTZXduZp1ODBPnnDGxuhhYaOJAyBf9Z9.woff2" "$FONTS/noto-serif-kr/NotoSerifKR-SemiBold.woff2"
fetch "$NOTO_GOOGLE/v34/3Jn7SDn90Gmq2mr3blnHaTZXduZp1ODBPnnDGxuhhYaODAuBf9Z9.woff2" "$FONTS/noto-serif-kr/NotoSerifKR-Bold.woff2"

echo "▸ JetBrains Mono"
JBM_BASE="https://cdn.jsdelivr.net/gh/JetBrains/JetBrainsMono@v2.304/fonts/webfonts"
fetch "$JBM_BASE/JetBrainsMono-Regular.woff2" "$FONTS/jetbrains-mono/JetBrainsMono-Regular.woff2"
fetch "$JBM_BASE/JetBrainsMono-Medium.woff2" "$FONTS/jetbrains-mono/JetBrainsMono-Medium.woff2"
fetch "$JBM_BASE/JetBrainsMono-Bold.woff2" "$FONTS/jetbrains-mono/JetBrainsMono-Bold.woff2"
fetch "https://raw.githubusercontent.com/JetBrains/JetBrainsMono/v2.304/OFL.txt" "$FONTS/jetbrains-mono/OFL.txt"

echo "▸ Generating offline.css"
cat > "$FONTS/offline.css" <<'CSS'
/* Generated by scripts/fetch-fonts.sh — do not edit by hand */

/* Pretendard Variable — SIL OFL 1.1 */
@font-face {
  font-family: 'Pretendard Variable';
  src: url('pretendard/PretendardVariable.woff2') format('woff2-variations');
  font-weight: 45 920;
  font-display: block;
  font-style: normal;
}

/* Noto Serif KR — SIL OFL 1.1 */
@font-face {
  font-family: 'Noto Serif KR';
  src: url('noto-serif-kr/NotoSerifKR-Light.woff2') format('woff2');
  font-weight: 300;
  font-display: block;
}
@font-face {
  font-family: 'Noto Serif KR';
  src: url('noto-serif-kr/NotoSerifKR-Medium.woff2') format('woff2');
  font-weight: 500;
  font-display: block;
}
@font-face {
  font-family: 'Noto Serif KR';
  src: url('noto-serif-kr/NotoSerifKR-SemiBold.woff2') format('woff2');
  font-weight: 600;
  font-display: block;
}
@font-face {
  font-family: 'Noto Serif KR';
  src: url('noto-serif-kr/NotoSerifKR-Bold.woff2') format('woff2');
  font-weight: 700;
  font-display: block;
}

/* JetBrains Mono — SIL OFL 1.1 */
@font-face {
  font-family: 'JetBrains Mono';
  src: url('jetbrains-mono/JetBrainsMono-Regular.woff2') format('woff2');
  font-weight: 400;
  font-display: block;
}
@font-face {
  font-family: 'JetBrains Mono';
  src: url('jetbrains-mono/JetBrainsMono-Medium.woff2') format('woff2');
  font-weight: 500;
  font-display: block;
}
@font-face {
  font-family: 'JetBrains Mono';
  src: url('jetbrains-mono/JetBrainsMono-Bold.woff2') format('woff2');
  font-weight: 700;
  font-display: block;
}
CSS

echo "✓ Fonts bundled → $FONTS"
echo "  Total size:"
du -sh "$FONTS" 2>/dev/null || true
echo ""
echo "To use in a theme, replace the CDN @import lines with:"
echo "  @import url('../../fonts/offline.css');"
