#!/usr/bin/env node
// Theme-Foundry orchestration helper.
//
// Commands:
//   brief <brand>      — print the "forge brief" (JSON) the theme-forger agent consumes
//   list [category]    — list all brands, optionally filtered
//   check <brand>      — verify a brand exists in registry
//   paths <brand>      — print the output paths (design.md + marp.css) for a brand
//   info <brand>       — human-readable summary of one brand
//
// Used by the theme-forger skill. Agents cannot directly generate files,
// so this script prepares everything they need and validates their output.

import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { homedir } from 'node:os';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PLUGIN_ROOT = join(__dirname, '..');
const REGISTRY_PATH = join(PLUGIN_ROOT, 'assets', 'design-systems', 'registry.json');

// v0.8.0+: user-generated themes cached in stable location that survives plugin upgrades.
// Priority env: CLAUDE_PLUGIN_DATA > ~/.marp-slide-studio
const DATA_DIR = process.env.CLAUDE_PLUGIN_DATA || join(homedir(), '.marp-slide-studio');
const USER_THEMES_DIR = join(DATA_DIR, 'themes');
// v0.7.1 and earlier wrote to this location — kept as a fallback lookup for backward compat
const LEGACY_GENERATED_DIR = join(PLUGIN_ROOT, 'assets', 'design-systems', 'generated');
// Seed themes (read-only reference examples shipped with plugin)
const SEED_DIR = join(PLUGIN_ROOT, 'examples', 'seed-themes');

function loadRegistry() {
  if (!existsSync(REGISTRY_PATH)) {
    die(`Registry not found at ${REGISTRY_PATH}`);
  }
  return JSON.parse(readFileSync(REGISTRY_PATH, 'utf8'));
}

function slugify(brand) {
  return brand.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

function die(msg, code = 1) {
  console.error(`forge-theme: ${msg}`);
  process.exit(code);
}

function loadTransformPrompt() {
  const p = join(PLUGIN_ROOT, 'assets', 'transform-prompt.md');
  return existsSync(p) ? readFileSync(p, 'utf8') : null;
}

function loadKoreanRules() {
  const p = join(PLUGIN_ROOT, 'assets', 'typography', 'korean-scale.md');
  return existsSync(p) ? readFileSync(p, 'utf8') : null;
}

function cmdBrief(brand) {
  const reg = loadRegistry();
  const entry = reg.brands[brand];
  if (!entry) die(`Unknown brand "${brand}" — run \`forge-theme list\` to see all`);

  const slug = slugify(brand);
  // v0.8.0+: output to stable user-data dir that survives plugin upgrades
  const outputDesignMd = join(USER_THEMES_DIR, `${slug}.design.md`);
  const outputMarpCss = join(USER_THEMES_DIR, `${slug}.marp.css`);
  const brief = {
    brand,
    slug,
    category: entry.category,
    track: entry.suggested_track,
    mood: entry.mood,
    signature: entry.signature,
    output: {
      design_md: outputDesignMd,
      marp_css: outputMarpCss,
      directory: USER_THEMES_DIR,
      note: 'v0.8.0+: output dir is ${CLAUDE_PLUGIN_DATA}/themes/ — persists across plugin upgrades. Create parent dir if missing.',
    },
    requires: {
      transform_prompt: 'assets/transform-prompt.md',
      cjk_scale: 'assets/typography/cjk-scale.md',
      latin_scale: 'assets/typography/latin-scale.md',
      mixed_language: 'assets/typography/mixed-language.md',
      layout_catalog: 'assets/layouts/README.md',
      anti_patterns: 'assets/anti-patterns.md',
      theme_foundation: 'assets/theme-foundation.css',
    },
    validation: {
      command: `node scripts/validate-theme.mjs "${outputMarpCss}"`,
      exit_zero_required: true,
    },
    attribution: `/* @theme ${slug} */\n/* Generated by marp-slide-studio theme-forger. Inspired by ${brand}. Not affiliated. */`,
  };
  console.log(JSON.stringify(brief, null, 2));
}

// Helper: check if a theme is cached anywhere (user > legacy > seed)
function findThemePath(slug) {
  for (const dir of [USER_THEMES_DIR, LEGACY_GENERATED_DIR, SEED_DIR]) {
    const p = join(dir, `${slug}.marp.css`);
    if (existsSync(p)) return { path: p, source: dir === USER_THEMES_DIR ? 'user-cache' : dir === LEGACY_GENERATED_DIR ? 'legacy' : 'seed' };
  }
  return null;
}

function cmdList(filter) {
  const reg = loadRegistry();
  const brands = Object.entries(reg.brands);
  const filtered = filter
    ? brands.filter(([_, v]) => v.category === filter)
    : brands;
  console.log(`${filtered.length} brand${filtered.length === 1 ? '' : 's'}${filter ? ' in category ' + filter : ''}:\n`);
  const byCategory = {};
  for (const [name, meta] of filtered) {
    (byCategory[meta.category] ||= []).push({ name, ...meta });
  }
  for (const [cat, list] of Object.entries(byCategory).sort()) {
    console.log(`  ${cat} (${list.length})`);
    for (const b of list) {
      const found = findThemePath(slugify(b.name));
      const mark = found ? (found.source === 'user-cache' ? '●' : found.source === 'seed' ? '◐' : '◑') : '○';
      console.log(`    ${mark} ${b.name.padEnd(16)} ${b.suggested_track.padEnd(20)} ${b.mood}`);
    }
  }
  console.log('\n  ● user-cache   ◐ seed example   ◑ legacy (will move on next forge)   ○ on-demand');
}

function cmdCheck(brand) {
  const reg = loadRegistry();
  if (!reg.brands[brand]) die(`Unknown: ${brand}`);
  console.log(`✓ ${brand} exists in registry`);
}

function cmdPaths(brand) {
  const reg = loadRegistry();
  if (!reg.brands[brand]) die(`Unknown: ${brand}`);
  const slug = slugify(brand);
  // v0.8.0+: writable output always goes to user-cache
  console.log(`design_md=${join(USER_THEMES_DIR, `${slug}.design.md`)}`);
  console.log(`marp_css=${join(USER_THEMES_DIR, `${slug}.marp.css`)}`);
  console.log(`data_dir=${DATA_DIR}`);
  // Lookup chain (read-only)
  const found = findThemePath(slug);
  if (found) {
    console.log(`cached_at=${found.path}`);
    console.log(`cached_source=${found.source}`);
  } else {
    console.log('cached_at=(not cached, forge required)');
  }
}

function cmdInfo(brand) {
  const reg = loadRegistry();
  const e = reg.brands[brand];
  if (!e) die(`Unknown: ${brand}`);
  console.log(`
  ${brand}
  ─────────────────────────────
  category        ${e.category}
  suggested track ${e.suggested_track}
  mood            ${e.mood}

  palette         ${e.signature.palette.join(', ')}
  density         ${e.signature.density}
  typography      ${e.signature.typography_direction}

  hallmarks:
${e.signature.hallmarks.map(h => '    • ' + h).join('\n')}

  accent behavior
    ${e.signature.accent_behavior}
`);
}

// ──────── Dispatch ────────
const [cmd, ...rest] = process.argv.slice(2);
switch (cmd) {
  case 'brief':  cmdBrief(rest[0]); break;
  case 'list':   cmdList(rest[0]); break;
  case 'check':  cmdCheck(rest[0]); break;
  case 'paths':  cmdPaths(rest[0]); break;
  case 'info':   cmdInfo(rest[0]); break;
  default:
    console.log(`Usage:
  forge-theme.mjs brief <brand>   — JSON brief for the theme-forger agent
  forge-theme.mjs list [category] — list all brands (optionally filtered)
  forge-theme.mjs check <brand>   — verify brand exists
  forge-theme.mjs paths <brand>   — print output file paths
  forge-theme.mjs info <brand>    — human-readable summary

Categories: ai-llm, automotive, backend, design-creative, dev-tools,
            fintech, media-consumer, productivity, travel-commerce
`);
    process.exit(cmd ? 1 : 0);
}
