#!/usr/bin/env node
// Theme-Foundry orchestration helper.
//
// Commands:
//   brief <brand>      — print the "forge brief" (JSON) the theme-forger agent consumes
//   list [category]    — list all brands, optionally filtered
//   check <brand>      — verify a brand exists in registry
//   paths <brand>      — print the output paths (design.md + marp.css) for a brand
//   info <brand>       — human-readable summary of one brand
//
// Used by the theme-forger skill. Agents cannot directly generate files,
// so this script prepares everything they need and validates their output.

import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PLUGIN_ROOT = join(__dirname, '..');
const REGISTRY_PATH = join(PLUGIN_ROOT, 'assets', 'design-systems', 'registry.json');
const GENERATED_DIR = join(PLUGIN_ROOT, 'assets', 'design-systems', 'generated');

function loadRegistry() {
  if (!existsSync(REGISTRY_PATH)) {
    die(`Registry not found at ${REGISTRY_PATH}`);
  }
  return JSON.parse(readFileSync(REGISTRY_PATH, 'utf8'));
}

function slugify(brand) {
  return brand.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

function die(msg, code = 1) {
  console.error(`forge-theme: ${msg}`);
  process.exit(code);
}

function loadTransformPrompt() {
  const p = join(PLUGIN_ROOT, 'assets', 'transform-prompt.md');
  return existsSync(p) ? readFileSync(p, 'utf8') : null;
}

function loadKoreanRules() {
  const p = join(PLUGIN_ROOT, 'assets', 'typography', 'korean-scale.md');
  return existsSync(p) ? readFileSync(p, 'utf8') : null;
}

function cmdBrief(brand) {
  const reg = loadRegistry();
  const entry = reg.brands[brand];
  if (!entry) die(`Unknown brand "${brand}" — run \`forge-theme list\` to see all`);

  const slug = slugify(brand);
  const brief = {
    brand,
    slug,
    category: entry.category,
    track: entry.suggested_track,
    mood: entry.mood,
    signature: entry.signature,
    output: {
      design_md: join('assets', 'design-systems', 'generated', `${slug}.design.md`),
      marp_css: join('assets', 'design-systems', 'generated', `${slug}.marp.css`),
    },
    requires: {
      transform_prompt: 'assets/transform-prompt.md',
      korean_scale: 'assets/typography/korean-scale.md',
      mixed_language: 'assets/typography/mixed-language.md',
      layout_catalog: 'assets/layouts/README.md',
      anti_patterns: 'assets/anti-patterns.md',
    },
    validation: {
      command: `node scripts/validate-theme.mjs assets/design-systems/generated/${slug}.marp.css`,
      exit_zero_required: true,
    },
    attribution: `/* @theme ${slug} */\n/* Generated by marp-slide-studio theme-forger. Inspired by ${brand}. Not affiliated. */`,
  };
  console.log(JSON.stringify(brief, null, 2));
}

function cmdList(filter) {
  const reg = loadRegistry();
  const brands = Object.entries(reg.brands);
  const filtered = filter
    ? brands.filter(([_, v]) => v.category === filter)
    : brands;
  console.log(`${filtered.length} brand${filtered.length === 1 ? '' : 's'}${filter ? ' in category ' + filter : ''}:\n`);
  const byCategory = {};
  for (const [name, meta] of filtered) {
    (byCategory[meta.category] ||= []).push({ name, ...meta });
  }
  for (const [cat, list] of Object.entries(byCategory).sort()) {
    console.log(`  ${cat} (${list.length})`);
    for (const b of list) {
      const cached = existsSync(join(GENERATED_DIR, `${slugify(b.name)}.marp.css`));
      const mark = cached ? '●' : '○';
      console.log(`    ${mark} ${b.name.padEnd(16)} ${b.suggested_track.padEnd(20)} ${b.mood}`);
    }
  }
  console.log('\n  ● = already generated/cached    ○ = on-demand');
}

function cmdCheck(brand) {
  const reg = loadRegistry();
  if (!reg.brands[brand]) die(`Unknown: ${brand}`);
  console.log(`✓ ${brand} exists in registry`);
}

function cmdPaths(brand) {
  const reg = loadRegistry();
  if (!reg.brands[brand]) die(`Unknown: ${brand}`);
  const slug = slugify(brand);
  console.log(`design_md=${join(GENERATED_DIR, `${slug}.design.md`)}`);
  console.log(`marp_css=${join(GENERATED_DIR, `${slug}.marp.css`)}`);
}

function cmdInfo(brand) {
  const reg = loadRegistry();
  const e = reg.brands[brand];
  if (!e) die(`Unknown: ${brand}`);
  console.log(`
  ${brand}
  ─────────────────────────────
  category        ${e.category}
  suggested track ${e.suggested_track}
  mood            ${e.mood}

  palette         ${e.signature.palette.join(', ')}
  density         ${e.signature.density}
  typography      ${e.signature.typography_direction}

  hallmarks:
${e.signature.hallmarks.map(h => '    • ' + h).join('\n')}

  accent behavior
    ${e.signature.accent_behavior}
`);
}

// ──────── Dispatch ────────
const [cmd, ...rest] = process.argv.slice(2);
switch (cmd) {
  case 'brief':  cmdBrief(rest[0]); break;
  case 'list':   cmdList(rest[0]); break;
  case 'check':  cmdCheck(rest[0]); break;
  case 'paths':  cmdPaths(rest[0]); break;
  case 'info':   cmdInfo(rest[0]); break;
  default:
    console.log(`Usage:
  forge-theme.mjs brief <brand>   — JSON brief for the theme-forger agent
  forge-theme.mjs list [category] — list all brands (optionally filtered)
  forge-theme.mjs check <brand>   — verify brand exists
  forge-theme.mjs paths <brand>   — print output file paths
  forge-theme.mjs info <brand>    — human-readable summary

Categories: ai-llm, automotive, backend, design-creative, dev-tools,
            fintech, media-consumer, productivity, travel-commerce
`);
    process.exit(cmd ? 1 : 0);
}
